#title: 各个击破
title: 赵四方的技术博客
author: 赵军旺
email: zhjwpku@gmail.com
d1: Trying to be an excellent programmer.
d2:  Keep looking, don't settle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  zhjwpku

# Build settings
markdown: kramdown

url: http://zhjwpku.com

timezone: Asia/Shanghai

years:
- "2016"

gems:
- jekyll-paginate
paginate: 10
#paginate_path: "/blog/page:num/"

# Google analytics
google_analytics: UA-86852184-1

#main_menu:
#- label: Home
#  url: /index.html
#- label: Ceph
#  url: /ceph.html
#- label: Docker
#  url: /docker.html
#- label: OpenStack
#  url: /opensstack.html
#- label: Tags
#  url: /tags.html

host: 0.0.0.0
